#!/usr/bin/env bash

function hl() {
    declare -A fg_color_map
    fg_color_map[black]=30
    fg_color_map[red]=31
    fg_color_map[green]=32
    fg_color_map[yellow]=33
    fg_color_map[blue]=34
    fg_color_map[magenta]=35
    fg_color_map[cyan]=36
    fg_color_map[gray]=90
    fg_color_map[lgray]=37

    fg_c=$(echo -e "\e[1;${fg_color_map[$1]}m")
    c_rs=$'\e[0m'
    sed -u s"/$2/$fg_c\0$c_rs/g"
}


cat - | hl red '.* E .*' | hl yellow '.* W .*' | hl lgray '.* I .*' | hl gray '.* F .*' | hl blue '.* U .*'
